### ISSUE TITLE
WindowServer: Config changes are not written to config file due to read-only filesystem

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2768]
Changing the theme or resolution is not being saved in `/etc/WindowServer/WindowServer.ini`. Broken in https://github.com/SerenityOS/serenity/commit/53647e347f379fd542d8de390d9b3729be31e45a (cc @bugaevc), probably needs another `fstab` change to fix.

**Comment by bugaevc** [comment]
See discussion in https://github.com/SerenityOS/serenity/pull/2666

**Comment by linusg** [comment]
I see, thanks. Putting all config values in `$HOME/WindowServer.ini` seems like a good idea :+1:

**Comment by Petelliott** [comment]
This also affects administration tools like `useradd` and `passwd` which can't put their files in `$HOME`

**Comment by linusg** [comment]
Fixed by https://github.com/SerenityOS/serenity/commit/b5633c69d3659689004392ba937b53bd1af81cbc.

**Comment by bugaevc** [comment]
It's not fixed. It now happens to work again, but that still doesn't make it right to write anon's settings to `/etc`

**Comment by linusg** [comment]
Let's make a new issue about that, "config changes are not written to config file due to read-only filesystem" is solved :)
