### ISSUE TITLE
Kernel: Running on-target tests without KVM is flaky

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#5541]
Using latest from #4921, the kernel (or the shell?) sporadically times out after 10 minutes while trying to execute the counter loop for what I can judge are two different reasons.

Note that the CI job is running with KVM off.

When calculating the loop, it sometimes gets an assertion failed on RefPtr. This is suspiciously the same assertion that triggers in the macOS tests...
https://github.com/ADKaster/serenity/runs/1992109722?check_suite_focus=true#step:19:325
```
Shell(80): Job entry 'expr 63 + 1' deleted in 323 ms
Shell(10): Job entry 'expr 63 + 1' deleted in 327 ms
[Shell(10:10)]: ASSERTION FAILED: old_ref_count > 0
[Shell(10:10)]: .././AK/RefCounted.h:73 in void AK::RefCountedBase::ref() const
[#0 Shell(10:10)]: 0xc01237cf  __assertion_failed(char const*, char const*, unsigned int, char const*) +0x145
[#0 Shell(10:10)]: 0xc044cd43  Kernel::Thread::from_tid(AK::DistinctNumeric<int, __ThreadID_tag, false, true, true, false, false, false>) +0x29b
[#0 Shell(10:10)]: 0xc03417a1  Kernel::Process::send_signal(unsigned char, Kernel::Process*) +0xdd
[#0 Shell(10:10)]: 0xc03c0549  Kernel::Process::do_kill(Kernel::Process&, int) +0x5bb
[#0 Shell(10:10)]: 0xc03c1543  Kernel::Process::sys$kill(int, int) +0x6db
[#0 Shell(10:10)]: 0xc036e6d9  syscall_handler +0x1f08
[#0 Shell(10:10)]: 0xc036c799  syscall_asm_entry +0x31
```

Separately (maybe separately..) the test runner script sometimes hangs in the shell while trying to calculate the same expr N + 1 subshells. One shell is blocked on read, the parent on select. In the images below, I started SystemMonitor as root from a shell, so shells 25 and 29 should be ignored :).

```
Shell(38): Job entry 'expr 0 + 1' deleted in 1337 ms
Shell(31): Job entry 'expr 0 + 1' deleted in 1353 ms
Shell(39): Job entry 'expr 1 + 1' deleted in 1828 ms
Shell(31): Job entry 'expr 1 + 1' deleted in 1844 ms
Shell(31): JShell(40): Job entry 'expr 2 + 1' deleted in 1152 ms
ob entry 'expr 2 + 1' deleted in 1125 ms
Shell(41): Job entry 'expr 3 + 1' deleted in 1656 ms
Shell(31): Job entry 'expr 3 + 1' deleted in 1739 ms
Shell(42): Job entry 'expr 4 + 1' deleted in 1572 ms
Shell(31): Job entry 'expr 4 + 1' deleted in 1681 ms
Shell(43): Job entry 'expr 5 + 1' deleted in 930 ms
Shell(31): Job entry 'expr 5 + 1' deleted in 939 ms
Shell(31): Job entry 'expr 6 + 1' deleted in 1376 ms
Shell(44): Job entry 'expr 6 + 1' deleted in 1444 ms
Shell(45): Job entry 'expr 7 + 1' deleted in 719 ms
Shell(31): Job entry 'expr 7 + 1' deleted in 729 ms
Shell(31): Job entry 'expr 8 + 1' deleted in 1590 ms
```

PID 46 is reading (he'll be job 'expr 9 + 1'):
![reader](https://user-images.githubusercontent.com/8388494/109373567-c7463400-786c-11eb-91b1-1e4b483c22d6.png)

PID 31 is selecting in the event loop waiting for SIGCHLD:
![selector](https://user-images.githubusercontent.com/8388494/109373642-58b5a600-786d-11eb-8c60-8a9bb4be23d5.png)

cc @alimpfard @tomuta (?)

**Comment by alimpfard** [comment]
The only explicit `read()` I can think of is the one for the sync pipe, with which the child waits for the parent shell to finish doing its redirections and set the tty process group.
I don't think (though I haven't looked at that bit of the code to definitively say) the parent shell does anything involving the event loop between forking and writing to that pipe.

**Comment by tomuta** [comment]
The problem is that currently it's possible for `read` to block when it shouldn't. I [rewrote](https://github.com/SerenityOS/serenity/pull/5184/commits/490c8a5cd5561d347248d778a43ddf490c5e8c21) the `Thead::ReadBlocker` and `Thread::WriteBlocker` in #5184 to solve this problem (because it causes a bunch of problems with multiple processors), but unfortunately it's a fairly large architectural change that requires major changes to FS/Net that I haven't done quite yet.

**Comment by tomuta** [comment]
There are many other odd problems that I fixed that can also contribute to this, or cause such problems. For example, context switches while holding locks etc that eventually either lead to deadlocks or the system stalling. All this is a whole lot more pronounced when running with multiple processors. Not all of these can happen on the current system where the Scheduler is running only on one processor, but some can.

**Comment by ADKaster** [comment]
Mmk. I'll push a commit to my PR that adds [`continue-on-error`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) to the `ninja run` step so that the test script timing out doesn't fail any builds until it can be stable. To be tracked in this issue :) .

**Comment by ADKaster** [comment]
Looks like the original issue here is still present, the one from the first comment:

from a local run:
```
TestIPv4Address(84:84): Finished 14 tests and 0 benchmarks in 436ms (10ms tests, 0ms benchmarks, 426ms other).
TestIPv4Address(84:84): Out of 14 tests, 14 passed and 0 failed.
Shell(90:90): Core::EventLoop: Failed to connect to InspectorServer
[#0 SyncTask(3:3)]: Ext2FS: Flushed 7 blocks to disk
[#0 SyncTask(3:3)]: Ext2FS: Flushed 6 blocks to disk
[#0 SyncTask(3:3)]: Ext2FS: Flushed 3 blocks to disk
TestNeverDestroyed(169:169): Completed test 'should_construct_by_copy' in 0ms
TestNeverDestroyed(169:169): Completed test 'should_construct_by_move' in 0ms
TestNeverDestroyed(169:169): Completed test 'should_not_destroy' in 0ms
TestNeverDestroyed(169:169): Completed test 'should_provide_dereference_operator' in 0ms
TestNeverDestroyed(169:169): Completed test 'should_provide_indirection_operator' in 0ms
TestNeverDestroyed(169:169): Completed test 'should_provide_basic_getter' in 0ms
TestNeverDestroyed(169:169): Finished 6 tests and 0 benchmarks in 182ms (0ms tests, 0ms benchmarks, 182ms other).
TestNeverDestroyed(169:169): Out of 6 tests, 6 passed and 0 failed.
Shell(175:175): Core::EventLoop: Failed to connect to InspectorServer
[Shell(175:175)]: ASSERTION FAILED: old_ref_count > 0
[Shell(175:175)]: ../.././AK/RefCounted.h:53 in void AK::RefCountedBase::ref() const
[#0 Shell(175:175)]: 0xc05d3bd8  abort +0x4b
[#0 Shell(175:175)]: 0xc05c6f21  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xd5
[#0 Shell(175:175)]: 0xc050b885  Kernel::Thread::from_tid(AK::DistinctNumeric<int, __ThreadID_tag, false, true, true, false, false, false>) +0x29d
[#0 Shell(175:175)]: 0xc03bc53c  Kernel::Process::send_signal(unsigned char, Kernel::Process*) +0x86
[#0 Shell(175:175)]: 0xc0449d08  Kernel::Process::do_kill(Kernel::Process&, int) +0x3f2
[#0 Shell(175:175)]: 0xc044bb1c  Kernel::Process::sys$kill(int, int) +0xb16
[#0 Shell(175:175)]: 0xc03ec578  syscall_handler +0x1e7d
[#0 Shell(175:175)]: 0xc03ea6c3  syscall_asm_entry +0x31
```

from a CI run:  https://github.com/SerenityOS/serenity/runs/2628383346?check_suite_focus=true#step:23:805
```
[Shell(9:9)]: ASSERTION FAILED: old_ref_count > 0
[Shell(9:9)]: .././AK/RefCounted.h:53 in void AK::RefCountedBase::ref() const
[#0 Shell(9:9)]: 0xc05d3be0  abort +0x4b
[#0 Shell(9:9)]: 0xc05c6f29  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xd5
[#0 Shell(9:9)]: 0xc050b88d  Kernel::Thread::from_tid(AK::DistinctNumeric<int, __ThreadID_tag, false, true, true, false, false, false>) +0x29d
[#0 Shell(9:9)]: 0xc03bc544  Kernel::Process::send_signal(unsigned char, Kernel::Process*) +0x86
[#0 Shell(9:9)]: 0xc0449d10  Kernel::Process::do_kill(Kernel::Process&, int) +0x3f2
[#0 Shell(9:9)]: 0xc044bb24  Kernel::Process::sys$kill(int, int) +0xb16
[#0 Shell(9:9)]: 0xc03ec580  syscall_handler +0x1e7d
[#0 Shell(9:9)]: 0xc03ea6cb  syscall_asm_entry +0x31
```

Fun times with #6459 

Steps to repro:
0) Grab the `run-tests-and-shutdown.sh` script from my branch that runs 107 tests instead of just 4.
1) Disable KVM/WHPX. All the fun bugs happen w/out HW acceleration
2) Run in CI in self-test mode
```
$ env | grep SERENITY
SERENITY_QEMU_BIN=/mnt/c/Program Files/qemu/qemu-system-i386.exe
SERENITY_KERNEL_CMDLINE=disable_virtio boot_mode=self-test
SERENITY_RUN=ci
SERENITY_DISK_IMAGE=\\wsl$\Ubuntu\home\andrew\serenity\Build\i686\_disk_image
SERENITY_QEMU_CPU=max,vmx=off
```
3) Loop until the party starts
```
export COMMAND="./Meta/serenity.sh run"
while $COMMAND; do :; done
```

**Comment by bgianfo** [comment]
As discussed on discord between @ADKaster / @tomuta and myself, it appears that this happens because we remove the thread from the `g_tid_map` in the `Thread` destructor. So we race between trying to lookup by TID and actually removing it from the list on destruction.

https://github.com/SerenityOS/serenity/blob/c1b2813ddf113cf84516fb1be818ea3fdffc8e94/Kernel/Thread.cpp#L126-L146

@tomuta suggested a potential fix: 
> tomuta — Today at 12:19 PM
> RefCounted::try_ref is what you want
> if (it->try_ref()) and then if that's true then adopt it
